// partyData.js — Comprehensive Indian political party profiles with official logos
// Logo sources: Wikimedia Commons (public domain / fair use)

const partyData = {
  "BJP": {
    fullName: "Bharatiya Janata Party",
    abbr: "BJP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Bharatiya_Janata_Party_logo.svg/180px-Bharatiya_Janata_Party_logo.svg.png",
    color: "#FF6B00",
    founded: 1980,
    founder: "Syama Prasad Mukherjee (predecessor Jan Sangh)",
    president: "J.P. Nadda",
    ideology: ["Right-wing", "Hindu Nationalism", "Integral Humanism"],
    alliance: "NDA (National Democratic Alliance)",
    headquarters: "6A, Deendayal Upadhyaya Marg, New Delhi",
    lsSeats: 240,
    rsSeats: 96,
    statesGoverned: 12,
    symbol: "Lotus",
    history: "Founded in 1980 as successor to the Bharatiya Jana Sangh. Rose to prominence under Atal Bihari Vajpayee and L.K. Advani. Has been in power at the centre since 2014 under PM Narendra Modi."
  },
  "INC": {
    fullName: "Indian National Congress",
    abbr: "INC",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Indian_National_Congress_hand_logo.svg/180px-Indian_National_Congress_hand_logo.svg.png",
    color: "#00BFFF",
    founded: 1885,
    founder: "Allan Octavian Hume",
    president: "Mallikarjun Kharge",
    ideology: ["Centre-left", "Social Democracy", "Secularism"],
    alliance: "INDIA (Indian National Developmental Inclusive Alliance)",
    headquarters: "24, Akbar Road, New Delhi",
    lsSeats: 99,
    rsSeats: 26,
    statesGoverned: 3,
    symbol: "Hand",
    history: "India's oldest political party, founded in 1885. Led the Indian independence movement. Governed India for most of the post-independence era under Nehru-Gandhi family leadership."
  },
  "AAP": {
    fullName: "Aam Aadmi Party",
    abbr: "AAP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Aam_Aadmi_Party_logo_%28English%29.svg/180px-Aam_Aadmi_Party_logo_%28English%29.svg.png",
    color: "#0072BC",
    founded: 2012,
    founder: "Arvind Kejriwal",
    president: "Arvind Kejriwal",
    ideology: ["Centre", "Populism", "Anti-corruption"],
    alliance: "INDIA",
    headquarters: "206, Deen Dayal Upadhyaya Marg, New Delhi",
    lsSeats: 3,
    rsSeats: 10,
    statesGoverned: 1,
    symbol: "Broom",
    history: "Born out of the anti-corruption movement led by Anna Hazare in 2011. Founded by Arvind Kejriwal in 2012. Governs Delhi and had a historic win in Punjab in 2022."
  },
  "TMC": {
    fullName: "All India Trinamool Congress",
    abbr: "TMC",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/All_India_Trinamool_Congress_logo.svg/180px-All_India_Trinamool_Congress_logo.svg.png",
    color: "#2E8B57",
    founded: 1998,
    founder: "Mamata Banerjee",
    president: "Mamata Banerjee",
    ideology: ["Centre-left", "Bengali Nationalism", "Secularism"],
    alliance: "INDIA",
    headquarters: "30B, Harish Chatterjee Street, Kolkata",
    lsSeats: 29,
    rsSeats: 13,
    statesGoverned: 1,
    symbol: "Flowers and Grass",
    history: "Founded by Mamata Banerjee after breaking away from Congress. Ended the 34-year Left Front rule in West Bengal in 2011. Dominant force in Bengal politics."
  },
  "SP": {
    fullName: "Samajwadi Party",
    abbr: "SP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Samajwadi_Party_logo.svg/180px-Samajwadi_Party_logo.svg.png",
    color: "#FF0000",
    founded: 1992,
    founder: "Mulayam Singh Yadav",
    president: "Akhilesh Yadav",
    ideology: ["Centre-left", "Social Democracy", "Socialism"],
    alliance: "INDIA",
    headquarters: "18, Copernicus Lane, New Delhi",
    lsSeats: 37,
    rsSeats: 4,
    statesGoverned: 0,
    symbol: "Bicycle",
    history: "Founded by Mulayam Singh Yadav in 1992. Major political force in Uttar Pradesh. Now led by Akhilesh Yadav who served as UP CM from 2012-2017."
  },
  "DMK": {
    fullName: "Dravida Munnetra Kazhagam",
    abbr: "DMK",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/DMK_Election_Symbol_-_Rising_Sun.svg/180px-DMK_Election_Symbol_-_Rising_Sun.svg.png",
    color: "#FF0000",
    founded: 1949,
    founder: "C.N. Annadurai",
    president: "M.K. Stalin",
    ideology: ["Centre-left", "Dravidian Politics", "Social Justice"],
    alliance: "INDIA",
    headquarters: "Anna Arivalayam, Chennai",
    lsSeats: 22,
    rsSeats: 10,
    statesGoverned: 1,
    symbol: "Rising Sun",
    history: "Founded in 1949 as part of the Dravidian movement. One of two major parties in Tamil Nadu. Currently in power under Chief Minister M.K. Stalin."
  },
  "TDP": {
    fullName: "Telugu Desam Party",
    abbr: "TDP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Telugu_Desam_Party_Flag.svg/180px-Telugu_Desam_Party_Flag.svg.png",
    color: "#FFFF00",
    founded: 1982,
    founder: "N.T. Rama Rao",
    president: "N. Chandrababu Naidu",
    ideology: ["Centre", "Telugu Pride", "Regionalism"],
    alliance: "NDA",
    headquarters: "NTR Trust Bhavan, Hyderabad",
    lsSeats: 16,
    rsSeats: 3,
    statesGoverned: 1,
    symbol: "Bicycle",
    history: "Founded by legendary actor N.T. Rama Rao in 1982. Major party in Andhra Pradesh. Chandrababu Naidu returned to power in AP in 2024."
  },
  "JD(U)": {
    fullName: "Janata Dal (United)",
    abbr: "JD(U)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Janata_Dal_%28United%29_Flag.svg/180px-Janata_Dal_%28United%29_Flag.svg.png",
    color: "#006400",
    founded: 1999,
    founder: "Sharad Yadav, Nitish Kumar",
    president: "Nitish Kumar",
    ideology: ["Centre", "Socialism", "Secularism"],
    alliance: "NDA",
    headquarters: "7, Jantar Mantar Road, New Delhi",
    lsSeats: 12,
    rsSeats: 5,
    statesGoverned: 1,
    symbol: "Arrow",
    history: "Split from Janata Dal in 1999. Dominant force in Bihar under Nitish Kumar. Key NDA ally."
  },
  "YSRCP": {
    fullName: "YSR Congress Party",
    abbr: "YSRCP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/YSRCP_Logo.svg/180px-YSRCP_Logo.svg.png",
    color: "#0000CD",
    founded: 2011,
    founder: "Y.S. Jagan Mohan Reddy",
    president: "Y.S. Jagan Mohan Reddy",
    ideology: ["Centre-left", "Social Welfare", "Populism"],
    alliance: "Neutral",
    headquarters: "Tadepalli, Amaravati, Andhra Pradesh",
    lsSeats: 4,
    rsSeats: 4,
    statesGoverned: 0,
    symbol: "Ceiling Fan",
    history: "Founded by Jagan Mohan Reddy after his father YS Rajasekhara Reddy's death. Won a landslide in AP in 2019 but lost power in 2024."
  },
  "BSP": {
    fullName: "Bahujan Samaj Party",
    abbr: "BSP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Elephant_BSP.svg/180px-Elephant_BSP.svg.png",
    color: "#0000FF",
    founded: 1984,
    founder: "Kanshi Ram",
    president: "Mayawati",
    ideology: ["Centre-left", "Ambedkarism", "Social Justice"],
    alliance: "Unaligned",
    headquarters: "12, Gurudwara Rakab Ganj Road, New Delhi",
    lsSeats: 0,
    rsSeats: 1,
    statesGoverned: 0,
    symbol: "Elephant",
    history: "Founded by Kanshi Ram for the empowerment of Dalits and OBCs. Mayawati served as UP CM four times. Once a major force in UP politics."
  },
  "SHS": {
    fullName: "Shiv Sena",
    abbr: "SHS",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Shiv_Sena_logo.svg/180px-Shiv_Sena_logo.svg.png",
    color: "#FF6600",
    founded: 1966,
    founder: "Bal Thackeray",
    president: "Eknath Shinde",
    ideology: ["Right-wing", "Marathi Pride", "Hindutva"],
    alliance: "NDA",
    headquarters: "Sena Bhavan, Dadar, Mumbai",
    lsSeats: 7,
    rsSeats: 3,
    statesGoverned: 1,
    symbol: "Bow and Arrow",
    history: "Founded by Bal Thackeray in 1966. Split in 2022 with Eknath Shinde faction recognized as official SHS by ECI. Major party in Maharashtra."
  },
  "NCP": {
    fullName: "Nationalist Congress Party",
    abbr: "NCP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Nationalist_Congress_Party_logo.svg/180px-Nationalist_Congress_Party_logo.svg.png",
    color: "#0000CD",
    founded: 1999,
    founder: "Sharad Pawar",
    president: "Ajit Pawar",
    ideology: ["Centre-left", "Nationalism", "Federalism"],
    alliance: "NDA",
    headquarters: "10, Bishamber Das Marg, New Delhi",
    lsSeats: 1,
    rsSeats: 2,
    statesGoverned: 0,
    symbol: "Clock",
    history: "Founded by Sharad Pawar after splitting from Congress. Split again in 2023 — Ajit Pawar faction joined NDA. Key force in Maharashtra."
  },
  "BJD": {
    fullName: "Biju Janata Dal",
    abbr: "BJD",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Biju_Janata_Dal_Logo.svg/180px-Biju_Janata_Dal_Logo.svg.png",
    color: "#006400",
    founded: 1997,
    founder: "Naveen Patnaik",
    president: "Naveen Patnaik",
    ideology: ["Centre", "Regionalism", "Social Welfare"],
    alliance: "Neutral",
    headquarters: "Sankha Bhawan, Bhubaneswar",
    lsSeats: 1,
    rsSeats: 9,
    statesGoverned: 0,
    symbol: "Conch",
    history: "Founded by Naveen Patnaik. Governed Odisha for 24 years (2000-2024). Lost power to BJP in 2024 state elections."
  },
  "RJD": {
    fullName: "Rashtriya Janata Dal",
    abbr: "RJD",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Rashtriya_Janata_Dal_logo.png/180px-Rashtriya_Janata_Dal_logo.png",
    color: "#006400",
    founded: 1997,
    founder: "Lalu Prasad Yadav",
    president: "Lalu Prasad Yadav",
    ideology: ["Centre-left", "Social Justice", "Secularism"],
    alliance: "INDIA",
    headquarters: "13, V.P. House, Rafi Marg, New Delhi",
    lsSeats: 4,
    rsSeats: 6,
    statesGoverned: 0,
    symbol: "Hurricane Lamp",
    history: "Founded by Lalu Prasad Yadav in 1997 after splitting from Janata Dal. Major opposition party in Bihar."
  },
  "CPI(M)": {
    fullName: "Communist Party of India (Marxist)",
    abbr: "CPI(M)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/CPI%28M%29_Logo.svg/180px-CPI%28M%29_Logo.svg.png",
    color: "#CC0000",
    founded: 1964,
    founder: "P. Sundarayya, E.M.S. Namboodiripad",
    president: "Sitaram Yechury (General Secretary)",
    ideology: ["Left-wing", "Marxism-Leninism", "Communism"],
    alliance: "INDIA",
    headquarters: "A.K. Gopalan Bhawan, New Delhi",
    lsSeats: 4,
    rsSeats: 5,
    statesGoverned: 1,
    symbol: "Hammer, Sickle and Star",
    history: "Split from CPI in 1964. Governed West Bengal for 34 years (1977-2011). Currently governs Kerala under Pinarayi Vijayan."
  },
  "CPI": {
    fullName: "Communist Party of India",
    abbr: "CPI",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/CPI_logo.svg/180px-CPI_logo.svg.png",
    color: "#CC0000",
    founded: 1925,
    founder: "M.N. Roy",
    president: "D. Raja (General Secretary)",
    ideology: ["Left-wing", "Marxism-Leninism"],
    alliance: "INDIA",
    headquarters: "Ajoy Bhawan, New Delhi",
    lsSeats: 2,
    rsSeats: 1,
    statesGoverned: 0,
    symbol: "Ears of Corn and Sickle",
    history: "India's oldest communist party, founded in 1925. Played a significant role in the independence movement and labour movements."
  },
  "JMM": {
    fullName: "Jharkhand Mukti Morcha",
    abbr: "JMM",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Jharkhand_Mukti_Morcha_Logo.svg/180px-Jharkhand_Mukti_Morcha_Logo.svg.png",
    color: "#006400",
    founded: 1972,
    founder: "Shibu Soren",
    president: "Shibu Soren",
    ideology: ["Centre-left", "Tribal Rights", "Regionalism"],
    alliance: "INDIA",
    headquarters: "Ranchi, Jharkhand",
    lsSeats: 3,
    rsSeats: 2,
    statesGoverned: 1,
    symbol: "Bow and Arrow",
    history: "Founded for tribal rights in Jharkhand. Hemant Soren serves as CM of Jharkhand."
  },
  "Lok Janshakti Party(Ram Vilas)": {
    fullName: "Lok Janshakti Party (Ram Vilas)",
    abbr: "LJP(RV)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/LJP%28RV%29_logo.png/180px-LJP%28RV%29_logo.png",
    color: "#0000CD",
    founded: 2021,
    founder: "Chirag Paswan",
    president: "Chirag Paswan",
    ideology: ["Centre-right", "Social Justice", "Dalit Empowerment"],
    alliance: "NDA",
    headquarters: "12, Janpath, New Delhi",
    lsSeats: 5,
    rsSeats: 0,
    statesGoverned: 0,
    symbol: "Helicopter",
    history: "Faction of LJP led by Chirag Paswan after split post Ram Vilas Paswan's death. Key NDA ally from Bihar."
  },
  "Janasena Party": {
    fullName: "Jana Sena Party",
    abbr: "JSP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Jana_Sena_Flag.svg/180px-Jana_Sena_Flag.svg.png",
    color: "#FF0000",
    founded: 2014,
    founder: "Pawan Kalyan",
    president: "Pawan Kalyan",
    ideology: ["Centre-right", "Telugu Pride"],
    alliance: "NDA",
    headquarters: "Vijayawada, Andhra Pradesh",
    lsSeats: 2,
    rsSeats: 0,
    statesGoverned: 0,
    symbol: "Glass Tumbler",
    history: "Founded by Telugu actor Pawan Kalyan. Allied with TDP-BJP in AP and won significant seats in 2024."
  },
  "BRS": {
    fullName: "Bharat Rashtra Samithi",
    abbr: "BRS",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/BRS_Party_logo.svg/180px-BRS_Party_logo.svg.png",
    color: "#FF69B4",
    founded: 2001,
    founder: "K. Chandrashekar Rao",
    president: "K. Chandrashekar Rao",
    ideology: ["Centre", "Telangana Pride", "Welfare"],
    alliance: "Neutral",
    headquarters: "Telangana Bhavan, Hyderabad",
    lsSeats: 2,
    rsSeats: 5,
    statesGoverned: 0,
    symbol: "Car",
    history: "Founded as TRS for Telangana statehood. Renamed to BRS in 2022. Governed Telangana from 2014-2023 under KCR."
  },
  "AIADMK": {
    fullName: "All India Anna Dravida Munnetra Kazhagam",
    abbr: "AIADMK",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/AIADMK_logo.svg/180px-AIADMK_logo.svg.png",
    color: "#FF0000",
    founded: 1972,
    founder: "M.G. Ramachandran",
    president: "Edappadi K. Palaniswami",
    ideology: ["Centre-right", "Dravidian Politics", "Populism"],
    alliance: "Unaligned",
    headquarters: "Royapettah, Chennai",
    lsSeats: 0,
    rsSeats: 4,
    statesGoverned: 0,
    symbol: "Two Leaves",
    history: "Founded by MGR after splitting from DMK. Jayalalithaa made it a dominant force. Currently in opposition in TN."
  },
  "JD(S)": {
    fullName: "Janata Dal (Secular)",
    abbr: "JD(S)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Janata_Dal_%28Secular%29.svg/180px-Janata_Dal_%28Secular%29.svg.png",
    color: "#006400",
    founded: 1999,
    founder: "H.D. Deve Gowda",
    president: "H.D. Deve Gowda",
    ideology: ["Centre-left", "Secularism", "Agrarianism"],
    alliance: "NDA",
    headquarters: "Bengaluru, Karnataka",
    lsSeats: 2,
    rsSeats: 1,
    statesGoverned: 0,
    symbol: "Woman Farmer Carrying Paddy on her Head",
    history: "Regional party of Karnataka led by the Deve Gowda family. H.D. Deve Gowda served as PM (1996-97). Joined NDA in 2024."
  },
  "Shiv Sena (Uddhav Balasaheb Thackrey)": {
    fullName: "Shiv Sena (Uddhav Balasaheb Thackeray)",
    abbr: "SS-UBT",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Shiv_Sena_logo.svg/180px-Shiv_Sena_logo.svg.png",
    color: "#FF6600",
    founded: 2022,
    founder: "Uddhav Thackeray",
    president: "Uddhav Thackeray",
    ideology: ["Right-wing", "Marathi Pride", "Hindutva"],
    alliance: "INDIA",
    headquarters: "Matoshree, Bandra, Mumbai",
    lsSeats: 9,
    rsSeats: 2,
    statesGoverned: 0,
    symbol: "Burning Torch",
    history: "Faction of Shiv Sena led by Uddhav Thackeray after the 2022 split. Part of the INDIA opposition alliance."
  },
  "Nationalist Congress Party - Sharadchandra Pawar": {
    fullName: "Nationalist Congress Party – Sharadchandra Pawar",
    abbr: "NCP-SP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Nationalist_Congress_Party_logo.svg/180px-Nationalist_Congress_Party_logo.svg.png",
    color: "#0000CD",
    founded: 2023,
    founder: "Sharad Pawar",
    president: "Sharad Pawar",
    ideology: ["Centre-left", "Nationalism", "Federalism"],
    alliance: "INDIA",
    headquarters: "Silver Oak, Mumbai",
    lsSeats: 8,
    rsSeats: 3,
    statesGoverned: 0,
    symbol: "Man Blowing Tutari",
    history: "Sharad Pawar's faction after the NCP split in 2023. Part of the INDIA alliance and MVA in Maharashtra."
  },
  "Asom Gana Parishad": {
    fullName: "Asom Gana Parishad",
    abbr: "AGP",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/AGP_logo.svg/180px-AGP_logo.svg.png",
    color: "#FFFFFF",
    founded: 1985,
    founder: "Prafulla Kumar Mahanta",
    president: "Atul Bora",
    ideology: ["Centre", "Assamese Regionalism"],
    alliance: "NDA",
    headquarters: "Guwahati, Assam",
    lsSeats: 1,
    rsSeats: 0,
    statesGoverned: 0,
    symbol: "Elephant",
    history: "Born from the Assam Movement (1979-85). Key regional party in Assam, currently allied with BJP."
  },
  "IND": {
    fullName: "Independent",
    abbr: "IND",
    logo: "",
    color: "#808080",
    founded: null,
    founder: "N/A",
    president: "N/A",
    ideology: ["Various"],
    alliance: "None",
    headquarters: "N/A",
    lsSeats: 7,
    rsSeats: 0,
    statesGoverned: 0,
    symbol: "Various (allotted by ECI)",
    history: "Independent candidates not affiliated with any political party. Some are influential leaders who contest without party ticket."
  },
  "CPI(ML)(L)": {
    fullName: "Communist Party of India (Marxist-Leninist) Liberation",
    abbr: "CPI(ML)(L)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/CPIML_Liberation_Logo.svg/180px-CPIML_Liberation_Logo.svg.png",
    color: "#CC0000",
    founded: 1974,
    founder: "Vinod Mishra",
    president: "Dipankar Bhattacharya (General Secretary)",
    ideology: ["Far-left", "Marxism-Leninism", "Revolutionary Socialism"],
    alliance: "INDIA",
    headquarters: "Patna, Bihar",
    lsSeats: 2,
    rsSeats: 0,
    statesGoverned: 0,
    symbol: "Hammer, Sickle and Red Star",
    history: "Naxalite-origin party that transitioned to parliamentary politics. Strong presence in Bihar's working-class areas."
  },
  "IUML": {
    fullName: "Indian Union Muslim League",
    abbr: "IUML",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Indian_Union_Muslim_League_Logo.jpg/180px-Indian_Union_Muslim_League_Logo.jpg",
    color: "#006400",
    founded: 1948,
    founder: "Muhammad Ismail",
    president: "K.M. Kader Mohideen",
    ideology: ["Centre-left", "Minority Rights", "Secularism"],
    alliance: "INDIA (UDF in Kerala)",
    headquarters: "Chennai",
    lsSeats: 3,
    rsSeats: 1,
    statesGoverned: 0,
    symbol: "Ladder",
    history: "One of the oldest parties representing Muslim minorities. Strong presence in Kerala and Tamil Nadu."
  },
  "Hindustani Awam Morcha (Secular)": {
    fullName: "Hindustani Awam Morcha (Secular)",
    abbr: "HAM(S)",
    logo: "",
    color: "#FFA500",
    founded: 2015,
    founder: "Jitan Ram Manjhi",
    president: "Jitan Ram Manjhi",
    ideology: ["Centre", "Dalit Empowerment"],
    alliance: "NDA",
    headquarters: "Patna, Bihar",
    lsSeats: 1,
    rsSeats: 0,
    statesGoverned: 0,
    symbol: "Whistle",
    history: "Founded by former Bihar CM Jitan Ram Manjhi. Represents Mahadalit community interests. NDA ally."
  },
  "United Peoples Party, Liberal": {
    fullName: "United People's Party Liberal",
    abbr: "UPPL",
    logo: "",
    color: "#FFD700",
    founded: 2019,
    founder: "Pramod Boro",
    president: "Pramod Boro",
    ideology: ["Centre", "Bodo Tribal Rights"],
    alliance: "NDA",
    headquarters: "Kokrajhar, Assam",
    lsSeats: 1,
    rsSeats: 0,
    statesGoverned: 0,
    symbol: "Book",
    history: "Bodo tribal party from Assam. Leads the Bodoland Territorial Council. Ally of BJP in Assam."
  }
};

// Get party info by abbreviation or full name
export function getPartyInfo(partyName) {
  if (!partyName) return null;
  // Direct key match
  if (partyData[partyName]) return partyData[partyName];
  // Try matching by abbreviation
  const byAbbr = Object.values(partyData).find(p => p.abbr === partyName);
  if (byAbbr) return byAbbr;
  // Try partial match
  const lower = partyName.toLowerCase();
  const byPartial = Object.values(partyData).find(p =>
    p.fullName.toLowerCase().includes(lower) || lower.includes(p.abbr.toLowerCase())
  );
  return byPartial || null;
}

// Get party color with fallback
export function getPartyColor(partyName) {
  const info = getPartyInfo(partyName);
  return info ? info.color : "#6B7280";
}

export default partyData;
